 export  const Transectiondata = [
    {
      key: '1',
      txnId: 'TXN-001234',
      userName: 'Jacob Jones',
      userUsername: '@jacobjones',
      userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jacob',
      userEmail: 'tangsh@yahoo.ca',
      clubName: 'Highgate Assembly',
      clubAvatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Highgate&backgroundColor=1e40af',
      date: '15/10/2024',
      amount: '$149.99',
      type: 'Class Payment',
      status: 'Completed',
      paymentMethod: 'Credit Card',
      description: 'Choreography Class - Monthly Subscription',
      adminCommission: '$22.50',
      clubEarnings: '$127.49',
      commissionRate: '15%',
    },
    {
      key: '2',
      txnId: 'TXN-001235',
      userName: 'Eleanor Pena',
      userUsername: '@eleanorpena',
      userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Eleanor',
      userEmail: 'paulv@sbcglobal.net',
      clubName: 'Kingswell Hall',
      clubAvatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Kingswell&backgroundColor=7c2d12',
      date: '14/10/2024',
      amount: '$89.00',
      type: 'Membership',
      status: 'Completed',
      paymentMethod: 'PayPal',
      description: 'Annual Membership Renewal',
      adminCommission: '$13.35',
      clubEarnings: '$75.65',
      commissionRate: '15%',
    },
    {
      key: '3',
      txnId: 'TXN-001236',
      userName: 'Courtney Henry',
      userUsername: '@courtneyhenry',
      userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Courtney',
      userEmail: 'michiel@comcast.net',
      clubName: 'Westhaven Trust',
      clubAvatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Westhaven&backgroundColor=dc2626',
      date: '14/10/2024',
      amount: '$199.99',
      type: 'Workshop',
      status: 'Pending',
      paymentMethod: 'Credit Card',
      description: 'Ballet Workshop - Weekend Session',
      adminCommission: '$30.00',
      clubEarnings: '$169.99',
      commissionRate: '15%',
    },
    {
      key: '4',
      txnId: 'TXN-001237',
      userName: 'Floyd Miles',
      userUsername: '@floydmiles',
      userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Floyd',
      userEmail: 'mfburgo@icloud.com',
      clubName: 'Windmere Clubhouse',
      clubAvatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Windmere&backgroundColor=059669',
      date: '13/10/2024',
      amount: '$75.00',
      type: 'Private Lesson',
      status: 'Completed',
      paymentMethod: 'Debit Card',
      description: 'Private Dance Lesson - 1 Hour',
      adminCommission: '$11.25',
      clubEarnings: '$63.75',
      commissionRate: '15%',
    },
    {
      key: '5',
      txnId: 'TXN-001238',
      userName: 'Annette Black',
      userUsername: '@annetteblack',
      userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Annette',
      userEmail: 'rbarreira@optonline.net',
      clubName: 'Silverwood Club',
      clubAvatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Silverwood&backgroundColor=c2410c',
      date: '13/10/2024',
      amount: '$49.99',
      type: 'Class Payment',
      status: 'Failed',
      paymentMethod: 'Credit Card',
      description: 'Hip Hop Basics - Single Class',
      adminCommission: '$7.50',
      clubEarnings: '$42.49',
      commissionRate: '15%',
    },
    {
      key: '6',
      txnId: 'TXN-001239',
      userName: 'Darrell Steward',
      userUsername: '@darrellsteward',
      userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Darrell',
      userEmail: 'aschmitz@gmail.com',
      clubName: 'Ashford Circle',
      clubAvatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Ashford&backgroundColor=ea580c',
      date: '12/10/2024',
      amount: '$299.00',
      type: 'Membership',
      status: 'Completed',
      paymentMethod: 'Bank Transfer',
      description: 'Yearly Premium Membership',
      adminCommission: '$44.85',
      clubEarnings: '$254.15',
      commissionRate: '15%',
    },
    {
      key: '7',
      txnId: 'TXN-001240',
      userName: 'Kristin Watson',
      userUsername: '@kristinwatson',
      userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kristin',
      userEmail: 'crobles@icloud.com',
      clubName: 'Stonegate Society',
      clubAvatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Stonegate&backgroundColor=1e40af',
      date: '12/10/2024',
      amount: '$120.00',
      type: 'Workshop',
      status: 'Completed',
      paymentMethod: 'Apple Pay',
      description: 'Contemporary Dance Workshop',
      adminCommission: '$18.00',
      clubEarnings: '$102.00',
      commissionRate: '15%',
    },
    {
      key: '8',
      txnId: 'TXN-001241',
      userName: 'Kathryn Murphy',
      userUsername: '@kathrynmurphy',
      userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kathryn',
      userEmail: 'camenisch@yahoo.ca',
      clubName: 'Brookfield League',
      clubAvatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Brookfield&backgroundColor=dc2626',
      date: '11/10/2024',
      amount: '$85.00',
      type: 'Class Payment',
      status: 'Pending',
      paymentMethod: 'Google Pay',
      description: 'Jazz Dance - Group Class Package (5 sessions)',
      adminCommission: '$12.75',
      clubEarnings: '$72.25',
      commissionRate: '15%',
    },
    {
      key: '9',
      txnId: 'TXN-001242',
      userName: 'Esther Howard',
      userUsername: '@estherhoward',
      userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Esther',
      userEmail: 'camenisch@yahoo.ca',
      clubName: 'Elmhurst Alliance',
      clubAvatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Elmhurst&backgroundColor=65a30d',
      date: '11/10/2024',
      amount: '$165.00',
      type: 'Private Lesson',
      status: 'Completed',
      paymentMethod: 'Credit Card',
      description: 'Private Lesson Package - 2 Hours',
      adminCommission: '$24.75',
      clubEarnings: '$140.25',
      commissionRate: '15%',
    },
    {
      key: '10',
      txnId: 'TXN-001243',
      userName: 'Marvin McKinney',
      userUsername: '@marvinmckinney',
      userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marvin',
      userEmail: 'camenisch@yahoo.ca',
      clubName: 'Harbourstone Union',
      clubAvatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Harbourstone&backgroundColor=b91c1c',
      date: '10/10/2024',
      amount: '$59.99',
      type: 'Class Payment',
      status: 'Completed',
      paymentMethod: 'Credit Card',
      description: 'Latin Dance Beginner Class',
      adminCommission: '$9.00',
      clubEarnings: '$50.99',
      commissionRate: '15%',
    },
  ];