  export const demoData = [
    {
      key: '1',
      userId: 487441,
      name: 'Shophia Carter',
      username: '@shophiacarter',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Shophia',
      email: 'shophia.carter@example.com',
      dateOfBirth: '10 Aug, 2021',
      clubs: 2,
      posts: 6,
      country: 'USA',
      status: 'Active',
      skills: 'Grip strength, Blackboards, Pole flow',
      experience: '3 years',
      experienceLevel: 'Mid Level',
      memberOfClub: 'Fusion Club',
      recentPosts: [
        {
          id: 1,
          title: 'Dance Fusion',
          image: 'https://images.unsplash.com/photo-1508700929628-666bc8bd84ea?w=400',
          date: '12 days ago'
        },
        {
          id: 2,
          title: 'Hip-Hop',
          image: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=400',
          date: '5 days ago'
        },
        {
          id: 3,
          title: 'Ballet Basics',
          image: 'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=400',
          date: '18 days ago'
        }
      ]
    },
    {
      key: '2',
      userId: 653518,
      name: 'Eleanor Pena',
      username: '@eleanorpena',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Eleanor',
      email: 'paulv@sbcglobal.net',
      dateOfBirth: '15 Mar, 2020',
      clubs: 3,
      posts: 5,
      country: 'Lisbon',
      status: 'Active',
      skills: 'Contemporary, Jazz, Modern',
      experience: '5 years',
      experienceLevel: 'Advanced',
      memberOfClub: 'Rhythm Club',
      recentPosts: []
    },
    {
      key: '3',
      userId: 651535,
      name: 'Courtney Henry',
      username: '@courtneyhenry',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Courtney',
      email: 'michiel@comcast.net',
      dateOfBirth: '22 Jul, 2019',
      clubs: 0,
      posts: 1,
      country: 'Buenos Aires',
      status: 'Disable',
      skills: 'Salsa, Tango',
      experience: '2 years',
      experienceLevel: 'Beginner',
      memberOfClub: 'None',
      recentPosts: []
    },
    {
      key: '4',
      userId: 487441,
      name: 'Floyd Miles',
      username: '@floydmiles',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Floyd',
      email: 'mfburgo@icloud.com',
      dateOfBirth: '05 Jan, 2021',
      clubs: 4,
      posts: 2,
      country: 'Nairobi',
      status: 'Active',
      skills: 'Breaking, Popping',
      experience: '4 years',
      experienceLevel: 'Mid Level',
      memberOfClub: 'Urban Dance Club',
      recentPosts: []
    },
    {
      key: '5',
      userId: 449003,
      name: 'Annette Black',
      username: '@annetteblack',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Annette',
      email: 'rbarreira@optonline.net',
      dateOfBirth: '30 Sep, 2020',
      clubs: 4,
      posts: 7,
      country: 'Oslo',
      status: 'Active',
      skills: 'Ballet, Contemporary',
      experience: '6 years',
      experienceLevel: 'Advanced',
      memberOfClub: 'Elite Dance Club',
      recentPosts: []
    },
  ];